[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[[redirects]]
  from = "/"
  to = "/daily-investment-tracker.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/daily-investment-tracker.html"
  status = 301

[[redirects]]
  from = "/portfolio"
  to = "/dual-portfolio.html"
  status = 200

[[redirects]]
  from = "/dataroma"
  to = "/dataroma-enhanced.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
